version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/dockerized/
hooks:
  BeforeInstall:
    - location: prepare.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: buildagain.sh
      timeout: 300
      runas: root
